# Generated by Django 6.1 on 2026-08-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_banner_discountcode_order_courier_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_gallery',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='product',
            name='variants',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
